# RAG pipeline

In [8]:
import os
import sys
import csv
import ast
import json
import numpy as np
import pandas as pd
from ast import literal_eval
from dotenv import load_dotenv
from llama_index.core import (
    Document,
    VectorStoreIndex,
    StorageContext,
    PromptTemplate,
    load_index_from_storage,
    set_global_handler
)
from llama_index.llms.vllm import Vllm
from llama_index.llms.google_genai import GoogleGenAI
from llama_index.core.node_parser import SentenceSplitter
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.settings import Settings
from llama_cloud import AsyncLlamaCloud

# logging
import logging
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger("httpcore").setLevel(logging.WARNING)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("llama_index.core").setLevel(logging.WARNING)
logging.getLogger("fsspec").setLevel(logging.WARNING)
set_global_handler("simple")

load_dotenv()
CACHE_DIR = "../parsed_cache"
os.makedirs(CACHE_DIR, exist_ok=True)

client = AsyncLlamaCloud(api_key=os.getenv("LLAMA_CLOUD_API_KEY"))

## Setup LLM and Embedding model

* For the LLM, use **Gemini** for local development and *vLLM* for production
* For the embedding model use **BAAI/bge-small-en-v1.5** for local and Qwen3

In [23]:
if os.getenv("APP_ENV") == "dev":
    embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
    llm = GoogleGenAI(model="gemini-2.5-flash-lite")
elif os.getenv("APP_ENV") == "prod":
    embed_model = HuggingFaceEmbedding(model_name="Qwen/Qwen3-Embedding-0.6B")
    llm = Vllm(
        model="Qwen3.5-122B-A10B-GGUF",
        tensor_parallel_size=4,
        max_new_tokens=100,
        vllm_kwargs={"swap_space": 1, "gpu_memory_utilization": 0.5},
    )

Settings.llm = llm
Settings.embed_model = embed_model

INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2486.84it/s]
BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

INFO:sentence_transformers.SentenceTransformer:1 prompt is loaded, with the key: query

# Parse the PDF

In [24]:
async def parse_documents_with_llamaparse(data_dir: str):
    documents = []

    for filename in os.listdir(data_dir):
        if not filename.endswith(".pdf"):
            continue

        cache_file = os.path.join(CACHE_DIR, f"{filename}.json")

        # load from cache
        if os.path.exists(cache_file):
            print(f"Loading cached parse for {filename}...")
            with open(cache_file, "r") as f:
                pages = json.load(f)

            for page in pages:
                documents.append(
                    Document(
                        text=page["text"],
                        metadata=page["metadata"]
                    )
                )
            continue

        # parse normally
        file_path = os.path.join(data_dir, filename)

        print(f"Uploading {filename} to LlamaCloud...")
        file_obj = await client.files.create(
            file=file_path,
            purpose="parse"
        )

        print("Parsing file...")
        result = await client.parsing.parse(
            file_id=file_obj.id,
            tier="cost_effective",
            version="latest",
            agentic_options={
                "custom_prompt": "This is an equipment manual..."
            },
            output_options={
                "markdown": {
                    "tables": {"output_tables_as_markdown": True},
                },
                "images_to_save": ["embedded"],
            },
            expand=["markdown"]
        )

        print("Saving to cache...")
        pages_to_save = []
        for page in result.markdown.pages:
            pages_to_save.append({
                "text": page.markdown,
                "metadata": {
                    "file_name": filename,
                    "page": page.page_number
                }
            })

            documents.append(
                Document(
                    text=page.markdown,
                    metadata={
                        "file_name": filename,
                        "page": page.page_number
                    }
                )
            )

        with open(cache_file, "w") as f:
            json.dump(pages_to_save, f)

    return documents

documents = await parse_documents_with_llamaparse("../data")

Loading cached parse for Getting_Started_with_SM_Datum_V7.2.4_2024_CT_EN.pdf...
Loading cached parse for User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf...

## Chunk the document and store the RAG index

NOTE: If the parsing or chunking strategy is changed it will NOT automatically update your existing stored index. It loads the old index with old chunks
* After applying a new parsing or chunking strategy, delete the old storage folder.

In [ ]:
# chunking
splitter = SentenceSplitter(
    chunk_size=512,
    chunk_overlap=50
)

print("Chunking documents into nodes...")
nodes = splitter.get_nodes_from_documents(documents)

# vector index
if os.path.exists("../storage"):
    print("Loading index from storage...")
    storage_context = StorageContext.from_defaults(persist_dir="../storage")
    index = load_index_from_storage(storage_context)
else:
    print("Creating new index...")
    index = VectorStoreIndex.from_documents(nodes)
    index.storage_context.persist("../storage")

Chunking documents into nodes...
Loading index from storage...

In [26]:
for node in nodes:
    print(f"{node.node_id}: {node.text}")

27c5aa17-cfc2-45ac-af02-5ad5c508f693: www.contrastech.com

# Getting Started with SM-Datum

![Icon of a camera lens](page_1_image_1_v2.jpg)

Ver 2.3.4 Mar. 2024

Vision System
a96bef05-3351-4a1e-b51b-20c3db8c0e98: ![Perfect](page_2_image_1_v2.jpg)

# Perfect

## Purpose of This Guide

This guide describes the function of the SM-Datum and how to use it and gives a detailed description of each tools. The information contained in the Manual is subject to change, without notice, due to firmware updates or other reasons. Please find the latest version of this Manual at the Contrastech website.Please read this guide before use.

Copyright ©2023
Hangzhou Contrastech Co., Ltd.
Tel: 86-571-89712238
Add.: No.8, Xiyuan 9th Road West Lake District, Hangzhou 310030 China

All rights reserved. The information contained herein is proprietary and is provided solely for the purpose of allowing customers to operate and/or service Contrastech manufactured equipment and is not to be released, reproduced, or used for any other purpose without written permission of Contrastech.

Throughout this manual, trademarked names might be used. We state herein that we are using the names to the benefit of the trademark owner, with no intention of infringement.

*Disclaimer*

The information and specifications described in this guide are subject to change without notice.

*Latest Version*

For the latest version of this guide, see the Download Center on our web site at:www.contrastech.com.

*Technical Support*

For technical support, e-mail: support@contrastech.com.

**Do not remove the camera’s serial number label**

If the label is removed and the serial number can’t be read from the camera’s registers, the warranty is void.

**Do not open the camera housing**

Do not open the housing. Touching internal components may damage them.

**Prevent ingress or insertion of foreign substances into the camera housing**

Prevent liquid, flammable, or metallic substances from entering the camera housing. If operated with any foreign substances inside, the camera may fail or cause a fire.

**Avoid electromagnetic fields**

Do not operate the camera in the vicinity of strong electromagnetic fields. Avoid electrostatic charging.

**Clean with care**

Avoid cleaning the sensor if possible.

**Handle this camera with care.**

Do not abuse the camera. Avoid striking, shaking, etc. The camera could be damaged by improper handling.

**Read the manual**

Read the manual carefully before using the camera.

Getting Start Guide with SM-Datum

2
fb79c731-654f-43f4-a38a-e73ccfce7e18: # Overview

## Introduction

SM-Datum is an application software designed for smart cameras. It is compatible with the SM2 series visual sensor and requires the firmware of version 2.0 or later.
After logging in to cameras via the Software, you can manage the cameras' projects, including creating, editing, deleting, copying, and switching projects. While editing projects, you can configure the camera parameters, base images, tools, and output parameters. Meanwhile, you can configure the I/O settings, communication settings, time settings, and password of the camera as well as upgrading its firmware. In addition, the Software supports monitoring the status of multiple cameras simultaneously.
The Software supports conducting visual detection on both the images stored in and imported into cameras.

## Key Features

- Easy installation: Requires no additional drivers.
- High compatibility: Compatible with 32/64-bit Windows 7, Windows 10, or Windows 11 operating system.
- User-oriented UI design: Guides users to edit projects with the Wizard.
- Camera Management: Supports managing multiple cameras and monitoring their working status.
- Mode division: Displays detection results in the running mode, displays function settings in the configuration mode.
- Visual detection: Conducts visual detection on the real-time images from cameras or the images imported into cameras.

## System Requirements

The SM-Datum requires that one of the following operating systems is installed on your computer:

### Recommended

- Operating system: 32/64-bit Windows 7, Windows 10, or Windows 11 operating system
- CPU: Intel i3-8100T
- RAM: 8 GB or more
- Graphics card: a dedicated graphics card with 1366×768 or higher resolution, the integrated graphics card is not supported
- NIC: Intel Pro1000, I210, and I350 series gigabit network interface card

### Minimum system requirements

- Operating system: 32/64-bit Windows 7 or Windows 10 operating system
- CPU: Intel E3845 1.91GHz
- RAM: 4 GB
- Graphics card: a 1366×768 dedicated graphics card, the integrated graphics card is not supported
- NIC: Intel Pro1000, I210, and I350 series gigabit network interface card

- The Software has been installed with the drivers required by the hardware.
43be3b03-2704-479d-b1e1-b128125146db: No others drivers are needed.
- Some anti-virus software might recognize the Software as a virus. Hence, it is recommended to add the Software into the allowlist of the anti-virus software or exit the anti-virus software before running the Software.

![CONTRASTECH logo](page_3_image_1_v2.jpg)

3 Getting Start Guide with SM-Datum
ccef748f-0d82-4b93-8f02-fb56c28fe780: # Network Settings

To make sure that the Software can run smoothly so that data can be transmitted stably, you need to configure the network before running it.

## For SM2 Series

To make sure that the Software and SM2 Series cameras can run smoothly so that data can be transmitted stably, you need to configure the network before running it.

### Steps

1. On your PC, open Control Panel, click Network and Internet > Network and Sharing Center > Change Adapter Settings, select the corresponding network port, and click Properties to enter the property settings page.

2. Double-click Internet Protocol Version 4 to set the IP address of your PC. It is recommended to set a static IP address for the network port so as to accelerate device search and connection. See the figure below for details.

![Internet Protocol Version 4 (TCP/IPv4) Properties window showing network configuration settings](page_4_image_3_v2.jpg)

3. Click Settings, select Link Speed or Advanced, set Speed and Duplex to Auto-negotiation or 100 Mbps full duplex to ensure that the network speed is above 100 Mbps.

Getting Start Guide with SM-Datum 4
b1b49087-bad5-4bd4-b0cc-075c7d0392f1: # Login Page

The login page will show up after launching the Software. You need to log in to a camera before controlling it.

You can refresh the camera list to show the enumerated cameras. You can select a camera to view basic information, edit IP address, reset password, etc.

## Camera List

The camera list is on the left side of the login page. All enumerated cameras will be listed.

Right-click a camera and click Stick on Top to stick the camera on the top of the list.

Select a camera to view the basic information about the camera, including the NIC that connects the camera, camera name, MAC address, IP Address, subnet mask, gateway, manufacturer, model, serial number, and firmware version. See the picture below.

![Login interface showing camera list and login form](page_5_image_1_v2.jpg)

## Enumerate Camera

The Software refreshes the camera list automatically. You can also click <u>↻</u> to refresh the list manually.

To add a remote camera, click <u>+</u>, type in the IP address, and click OK. See the picture below.

![Add Camera Remotely dialog box](page_5_image_2_v2.jpg)

> **i** Make sure the connection between the remote camera and the PC is established when adding remote cameras.

5

Getting Start Guide with SM-Datum
9df61ffd-cef1-4b69-9a59-48343b27cdd2: # Camera List

## Camera Status

Different icons of the camera represent different camera status.

| Icon                                                       | Status      | Definition                                                                                                                                  |
| ---------------------------------------------------------- | ----------- | ------------------------------------------------------------------------------------------------------------------------------------------- |
| ![Camera icon](page_6_image_1_v2.jpg)                      | Available   | The camera is available. You can log into the camera.                                                                                       |
| ![Camera icon with red circle](page_6_image_1_v2.jpg)      | Occupied    | The camera is occupied by another process. Log out the camera from the current process before you can log into the camera via the Software. |
| ![Camera icon with yellow triangle](page_6_image_1_v2.jpg) | Unreachable | The camera's IP address is not reachable on the LAN. Edit the IP address before you can log into the camera.                                |
## Edit IP Address

You can edit the IP address of a camera.

### Before You Start

Camera status is Available or Unreachable.

### Steps

1. Right-click the camera you want to edit IP address.

2. Click Edit IP Address or click <u>✎</u> beside the IP address, subnet mask, or gateway information to show the Edit IP Address window.

3. Select an IP type according to actual needs.

4. Click OK.

![Edit IP Address Window Screenshot](page_6_image_1_v2.jpg)

| IP Type   | Description                                                                                                            |
| --------- | ---------------------------------------------------------------------------------------------------------------------- |
| Static IP | The camera will communicate with the PC via the IP address, subnet mask, and default gateway you specify. Recommended. |
| DHCP      | Camera IP address is negotiated with the PC and allocated automatically. Factory default.                              |
| LLA       | Camera IP address is negotiated with the PC and the network segment is 169.254.                                        |
<i> If you change the IP type, the camera will reboot automatically to make it effective. </i>

Getting Start Guide with SM-Datum 6
3d85548d-783f-459a-89e4-079e09c6c697: ## Log Into Camera

Before you can control a camera, you need to log in to the camera.

### Before You Start

Make sure the camera status is Available.

### Steps

1. Select the camera you want to log in.

2. Select a role you want to log in as. You can choose from Administrator, Technician, Maintainer, and Operator.

Why the Software cannot enumerate my camera? Possible Cause: .

3. Enter the password in <img src="iihw" alt="lock icon"> .

> The default password is Abc1234. We highly recommend you to change the password after the first login to ensure the security of your device.

Solution:

> The password strength of the device can be automatically checked. We highly recommend you change the password of your own choosing (using a minimum of 8 characters, including at least three kinds of following categories: upper case letters, lower case letters, numbers, and special characters) in order to increase the security of your product. And we recommend you change your password regularly, especially in the high security system, changing the password monthly or weekly can better protect your product. Proper configuration of all passwords and other security settings is the responsibility of the service provider and/or end-user.

4. Optional: Check Remember me to remember the password.

> If you forget the password, you can click Forgot password to reset a password. See details in Reset Password.

5. Click <img src="tvip" alt="arrow right icon"> or hit the Enter key to log in to the camera.

6. Optional: Click <img src="nupr" alt="gear icon"> to switch the camera.

## Reset Password

If you forgot the password of a camera, you can reset the password.

ve wiay panom
Why is the image stuck / in low frame / separated in the live view panel?

### Steps

1. Select the camera you want to reset password.

2. Click Forgot password to show the password reset window.

Make sure that the network transmission speed is 10oMbps or above

Question: Why is the image failed to be displayed in the preview window?
Possible Cause: The trigger mode is enabled. but no trigger signal is sent
Solution:
3. Contact our technical support to get the password reset file.
a06d7292-0828-441f-a035-2f5464687707: Possible Cause: The trigger mode is enabled. but no trigger signal is sent
Solution:
3. Contact our technical support to get the password reset file. If you choose to send an email, please include the serial number of the camera in the content.
4. After getting the password reset file, click Import Resetting File.
5. Click Open to load the key file and reset the password.
> The camera password will be restored to Abc1234. We highly recommend you change the password after login to ensure the security of your device.

No.8 Xiyuan 9th Road, West Lake District Hangzhou Zhejiang 310030 China
Tel: 86-571-89712238
www.contrastech.com
For Research Use Only ©2023 Hangzhou Contrastech Co., Ltd
All rights reserved. All trademarks are the property of Hangzhou Contrastech Co., Ltd.

7 Getting Start Guide with SM-Datum
99e5a6dc-aac5-4442-8e8b-04b77e04e963: # Interface Introduction

After login, the Software will load the last running project by default. If there is no project in the camera, the Software will create a blank project and run it. See the introduction of the main interface below.

| No. | Name                  | Description                                                                                                                                                                                        |
| --- | --------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1   | Menu Bar              | Project management, communication settings, camera settings (basic information, time synchronization, etc.), IO settings, operation management (device and software logs), and camera monitoring.  |
| 2   | Project Control Panel | View project running status in real time, reset project statistics, run/stop project, and edit project.                                                                                            |
| 3   | Tool List             | View the real-time status of each tool in the project and edit tools.                                                                                                                              |
| 4   | Live View Panel       | View the image of the camera in Camera Mode or imported image in Image Mode.                                                                                                                       |
| 5   | Current Role          | Display the current role, modify password, switch roles, and manage roles.                                                                                                                         |
| 6   | Resource Information  | View the memory usage, smart memory usage, and the CPU usage.<br/>Memory usage refers to system memory usage, and smart memory usage refers to usage of MMZ (Media Memory Zone) for the algorithm. |
| 7   | More                  | Check user manual and software version. Minimize, maximize, and exit the Software.                                                                                                                 |
c0507b47-035a-4fd8-bfc3-4cd7e75f98f7: <div style="display: flex; align-items: center;">
  <div style="background-color: blue; color: white; width: 30px; height: 30px; border-radius: 50%; display: flex; justify-content: center; align-items: center; margin-right: 10px; font-weight: bold;">i</div>
  <div>You can run multiple instances of the Software at the same time, but each instance can log into one camera only.</div>
</div>

## Menu Bar

Before using GigE Vision cameras, you should make sure that the cameras and the PC are on the same subnet, and that the Jumbo Frame functionality has been enabled in the Windows system.

### Camera Management

Log in to the camera, and switch the camera. See details in Log Into Camera.

### Project

Add, delete, import, export, and switch projects in the camera. See details in Project Management.

### Communication

Add, set, or delete different communication tools for the camera. See details in Communication Settings.

### Camera Settings

View camera basic information, synchronize time, etc. See details in Camera Settings.

### IO Settings

Allocate IO signals, and configure project switch and project output. See details in IO Settings.

### Operation Management

Search and export camera or software logs. Search, export, or delete images stored in the camera or imported to the camera. See details in Operation Management.

### Camera Monitoring

Start live view of one or multiple connected cameras in a window. And manage cameras, including displaying camera list, logging in to the camera, switching the live view window division and so on. See details in Camera Monitoring.

Getting Start Guide with SM-Datum

8
587ea5a7-2e66-4772-9f99-be82e5c4bf89: ## Project Control Panel

Project control panel shows the running result of the current project. You can control the project here
When in Camera Mode:

![Project Control Panel screenshot showing NG status, Project1 name, Total: 0, NG: 0, Reset button, Run Once, Run, and Edit buttons](page_9_image_3_v2.jpg)

When in Image Mode:

![Project Control Panel screenshot showing NG status, Project1 name, Total: 0, NG: 0, Reset button, Run, RunAll, and Edit buttons](page_9_image_4_v2.jpg)

![Contrastech logo](page_9_image_6_v2.jpg)

Description:

**OK/NG (upper-left)**

Real-time running result of the current project.

**Total**

Total running times of the current project.

**NG**

Total NG times of the current project.

**Reset**

Reset the count to zero.

**Run Once (Camera Mode)**

Run the project one time.

**Run/Stop**

Run the project continuously or stop running.

![Contrastech logo](page_9_image_2_v2.jpg)

**RunAll (Image Mode)**

Run the project for all imported images.

**Edit**

Enter the project configuration page to edit the project. Refer to Create a Project for details.

![Contrastech logo](page_9_image_5_v2.jpg)

![Contrastech logo](page_9_image_1_v2.jpg)

Hangzhou Contrastech Co., Ltd
No.8 Xiyuan 9th Road, West Lake District Hangzhou Zhejiang 310030 China
Tel: 86-571-89712238
www.contrastech.com
For Research Use Only ©2023 Hangzhou Contrastech Co., Ltd
All rights reserved. All trademarks are the property of Hangzhou Contrastech Co., Ltd.

CONTRASTECH

9 Getting Start Guide with SM-Datum
8b66ed58-838f-4393-afc3-199cede37a70: ## Tool List

Tool list shows the tools of the current project and their running status. You can quick edit each tool here.
Click <mark>📊</mark> in the upper-right corner to switch the view between list view and statistic view. List View:

![Screenshot showing 'Tools' interface with 'Edge Count6' and 'Pattern Existence7' items](page_10_image_2_v2.jpg)

Left: tool name and OK condition; Right: tool settings and running result Statistic View:

![Screenshot showing 'Tools' interface with 'Edge Count6' and 'Pattern Existence' statistics panels](page_10_image_1_v2.jpg)

Upper-left: tool name; Lower-left: OK condition; Upper-right: tool settings; Lower-right: running result; Center: statistics data
Different types of tools have different statistic graph:
* If the result is judged by the count or similarity, the x-axis is the judging range and the green area is OK. You can drag <mark>🟩</mark> to adjust the OK range.
* If the result is judged by existing or not, the statistic graph will show the count of OK and NG.
Click <mark>⚙️</mark> to edit the tool.

In [27]:
# basic retriever
retriever = index.as_retriever(similarity_top_k=5)

print("Querying the index...")
query_engine = RetrieverQueryEngine.from_args(
    retriever,
    llm=llm
)

print("Generating response...")
response = await query_engine.aquery(
    "What is the name of this device?"
)
print(response)

Querying the index...
Generating response...
INFO:google_genai.models:AFC is enabled with max remote calls: 10.
** Messages: **
system: You are an expert Q&A system that is trusted around the world.
Always answer the query using the provided context information, and not prior knowledge.
Some rules to follow:
1. Never directly reference the given context in your answer.
2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines.
user: Context information is below.
---------------------
file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 6

Equipment shown in Fig. 1-2

Double-click the SM-Datum shortcut on the desktop to open up the client software.

| Color  | Pin | Signal    | Signal Source | Designation                                                                    | Cable type               |
| ------ | --- | --------- | ------------- | ------------------------------------------------------------------------------ | ------------------------ |
| Red    | 1   | POWER\_IN | -             | Direct current power supply positive                                           | 8-pin terminal           |
| Brown  | 2   | GND       | Line 0/1/2/3- | Direct current power supply negative                                           | 8-pin terminal           |
| Purple | 3   | -         | -             | -                                                                              | Do not use it for wiring |
| Green  | 4   | RS-232 TX | -             | RS-232 serial port output

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 5

I/O and serial ports

| Pin | Signal    | Signal Source | Designation                                                                    | Cable                    |
| --- | --------- | ------------- | ------------------------------------------------------------------------------ | ------------------------ |
| 1   | POWER\_IN | -             | Direct current power supply positive                                           | 8-pin terminal           |
| 2   | OUT\_COM  | -             | Output signal ground                                                           | 8-pin terminal           |
| 3   | -         | -             | -                                                                              | Do not use it for wiring |
| 4   | RS-232 TX | -             | RS-232 serial port output                                                      | DB9 female serial port   |
| 5   | RS-232 RX | -             | RS-232 serial port input                                                       | DB9 female serial port   |
| 6   | MDI0+     | -             | Fast Ethernet signal MDI0+                                                     | RJ45 Ethernet connector  |
| 7   | MDI1-     | -             | Fast Ethernet signal MDI1-                                                     | RJ45 Ethernet connector  |
| 8   | GPIO2     | Line 2+       | Non-isolated input                                                             | 8-pin terminal           |
| 9   | IN\_COM   | -             | Input signal ground                                                            | 8-pin terminal           |
| 10  | GPIO3     | Line 3+       | Non-isolated output                                                            | 8-pin terminal           |
| 11  | GND       | -             | Direct current power supply negative                                           | 8-pin terminal           |
| 12  | -         | -             | -                                                                              | Do not use it for wiring |
| 13  | -         | -             | -                                                                              | Do not use it for wiring |
| 14  | MDI0-     | -             | Fast Ethernet signal MDI0-                                                     | RJ45 Ethernet connector  |
| 15  | MDI1+     | -             | Fast Ethernet signal MDI1+                                                     | RJ45 Ethernet connector  |
| 16  | GPIO0     | Line 0+       | Bi-directional non-isolated I/O, and it is the trigger by default.

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 9

|
| ----------------------------------- | -------------- |
| Subnet Mask                         | 255.255.255.0  |
| Default Gateway                     | 169.254.58.254 |
| How often did/does the issue occur? |                |

# Electrical Features

| Parameter Name                | Value   |
| ----------------------------- | ------- |
| Opto-Isolated Turn-On Voltage | 2 V     |
| Input Falling Delay           | 81.6 μs |
| Input Rising Delay            | 7 μs    |

To ensure the security of your device, if you forgot the password of a camera, you can click Forgot password to show the password reset window. Contact our technical support to get the password reset file. If you choose to send an email, please include the serial number of the camera in the content. After getting the password reset file, click Import Resetting File. Click Open to load the key file and reset the password.

# Contact Information

Hangzhou ContrasTech Co., Ltd

No.8 Xiyuan 9th Road, West Lake District Hangzhou Zhejiang 310030 China

Tel: 86-571-89712238

Contact: +86 571 86888309

Website: www.contrastech.com

Email: support@visiondatum.com

For Research Use Only ©2024 Hangzhou Contrastech Co., Ltd. All rights reserved. All trademarks are the property of Hangzhou Contrastech Co., Ltd.

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 3

# Status LED Description

| Status LED    | Description                                                                                                                                            |
| ------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------ |
| PWR Indicator | It is a power indicator. The indicator is red during the device’s power-on process. After the device is powered on, the indicator is green.            |
| LNK Indicator | It is a network status indicator. The indicator is flashing green when the network transmission is normal. Otherwise, it is unlit.                     |
| STS Indicator | It is a status indicator. The indicator is green when the device operates normally. When errors occur during the device starts or operates, it is red. |

Contact our technical support to get the resetting file.

Camera Serial No. J94219768

Contact: +86 571 86888309

Email: support@visiondatum.com

Website: www.contrastech.com

Import Resetting File

For Research Use Only ©2024 Hangzhou Contrastech Co., Ltd. All rights reserved. All trademarks are the property of Hangzhou Contrastech Co., Ltd.

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 5

and it is the trigger by default.             | 8-pin terminal           |
| 17  | GPIO1     | Line 1+       | Bi-directional non-isolated I/O, and it is used to switch projects by default. | 8-pin terminal           |

Contact our technical support to get the resetting file.

Hangzhou ContrasTech Co., Ltd

No.8 Xiyuan 9th Road, West Lake District Hangzhou Zhejiang 310030 China

Contact: +86 571 86888309

Tel: 86-571-89712238

Email: support@visiondatum.com

Website: www.contrastech.com

# Power and I/O Interface Definition
---------------------
Given the context information and not prior knowledge, answer the query.
Query: What is the name of this device?
Answer:
**************************************************
** Response: **
assistant: The device is an SM2 SE Camera CT.
**************************************************


The device is an SM2 SE Camera CT.

# RAG Evaluation

In [21]:
# # add a new question to the csv
# with open("../eval_dataset.csv", "a", newline="", encoding="utf-8") as csvfile:
#     writer = csv.writer(csvfile)
#     writer.writerow([
#         "",
#         "",
#         [""]
#     ])

In [17]:
eval_dataset = pd.read_csv("../eval_dataset.csv")
eval_dataset

,document,question,ground_truth,contexts
0,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,What is the order model number for the M12 cable?,['The order model number for the 17-pin M12 ca...,['### 17-pin M12 Cable with Fast Ethernet Inte...
1,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,What are the dimensions of the M12-mount housi...,['The dimensions of the M12-mount housing vari...,['Fig. 1-1: $46 \times 57.6 \times 25$ mm Mech...
2,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,What are all the pins on the 17-pin connector ...,['The pins on the 17-pin connector that should...,['| Purple White | 3 | - | - ...
3,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,What communication protocols does the SM2 seri...,['The SM2 series smart cameras supports Serial...,"['* Support Serial, TCP, UDP, FTP, Modbus and ..."
4,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,List all the LED indicators and what each colo...,"[""The LED indicators and their meanings are as...","[""| PWR Indicator | It is a power indicator. T..."
5,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,What are the step-by-step instructions to inst...,[''],['']
6,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,How do you add a remote camera in SM-Datum?,[''],['']
7,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,How does the wiring differ when connecting a P...,[''],['']
8,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,I want to use GPIO0 as an output. What needs t...,[''],['']
9,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,I want to connect 8 NPN photoelectric sensors ...,[''],['']
10,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,Is the SM2 SE camera compatible with GigE Visi...,['The manual mentions these for the LEO series...,['LEO series industrial cameras compatible wit...
11,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,Can the IO box V1.0 upgrade non-isolated IO to...,['No. This function is only supported by the I...,['| V1.0 | The IO box can be used for switchin...
12,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,What frame rate does the SM2 SE camera support?,['The manual does not specify the exact frame ...,['']
13,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,My camera isn't showing up in the software. wh...,[''],['']
14,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,The live image looks completely black. How do ...,[''],['']
15,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,I want to trigger the camera from a PLC. what ...,[''],['']
16,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,How do I connect this camera to my network?,[''],['']
17,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,I need to output results to another machine. w...,[''],['']
18,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,My image keeps freezing during preview,[''],['']

In [18]:
# convert stringified lists into real Python lists
eval_dataset["contexts"] = eval_dataset["contexts"].apply(ast.literal_eval)

# remove rows where contexts is empty or only contains empty strings
eval_dataset = eval_dataset[
    eval_dataset["contexts"].apply(
        lambda x: isinstance(x, list) and any(str(item).strip() for item in x)
    )
]

## Evaluate Retrieval

In [20]:
def normalize(text: str) -> str:
    """Light normalization: collapse whitespace, lowercase."""
    import re
    text = text.lower()
    text = re.sub(r'\s+', ' ', text)  # collapse newlines, tabs, extra spaces
    return text.strip()

def cosine_similarity(vec_a: list[float], vec_b: list[float]) -> float:
    a, b = np.array(vec_a), np.array(vec_b)
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-10))

def is_relevant(
    retrieved_chunk: str,
    gt_chunks: list[str],
    embed_model,
    threshold: float
) -> bool:
    """
    A retrieved chunk is relevant if its cosine similarity to ANY
    ground truth chunk exceeds the threshold.
    """
    retrieved_vec = embed_model.get_text_embedding(normalize(retrieved_chunk))
    for gt_chunk in gt_chunks:
        gt_vec = embed_model.get_text_embedding(normalize(gt_chunk))
        if cosine_similarity(retrieved_vec, gt_vec) >= threshold:
            return True
    return False

In [45]:
def evaluate_retrieval(
    retriever,
    eval_dataset: pd.DataFrame,
    embed_model,
    threshold: float = 0.80,
    k: int = 5,
) -> dict:
    """
    Evaluate retrieval using MRR@K and Recall@K.
    """
    results = []

    for _, row in eval_dataset.iterrows():
        question = row["question"]

        # contexts column may be stored as a string representation of a list
        gt_chunks = row["contexts"]
        if isinstance(gt_chunks, str):
            gt_chunks = literal_eval(gt_chunks)

        # retrieve top-K chunks
        retrieved_nodes = retriever.retrieve(question)
        retrieved_chunks = [node.get_content() for node in retrieved_nodes[:k]]

        # Binarize relevance for each retrieved chunk
        relevance_list = [
            1 if is_relevant(chunk, gt_chunks, embed_model, threshold) else 0
            for chunk in retrieved_chunks
        ]

        # MRR
        rr = 0.0
        for rank, rel in enumerate(relevance_list, start=1):
            if rel == 1:
                rr = 1.0 / rank
                break

        # Recall@K
        recall = 1.0 if any(relevance_list) else 0.0

        results.append({
            "question": question,
            "contexts": row["contexts"],
            "document": row["document"],
            "retrieved_chunks": retrieved_chunks,
            "gt_chunks": gt_chunks,
            "relevance_list": relevance_list,
            "reciprocal_rank": rr,
            "recall": recall,
            "num_relevant": sum(relevance_list),
        })

    # --- Aggregate ---
    mrr = float(np.mean([r["reciprocal_rank"] for r in results]))
    recall_at_k = float(np.mean([r["recall"] for r in results]))

    print(f"Overall MRR@{k}:     {mrr:.4f}")
    print(f"Overall Recall@{k}:  {recall_at_k:.4f}")

    summary = {
        f"MRR@{k}": round(mrr, 4),
        f"Recall@{k}": round(recall_at_k, 4),
        "threshold_used": threshold,
        "num_questions": len(results),
        "per_question": results,
    }

    return summary

In [46]:
results = evaluate_retrieval(
    retriever=retriever,
    eval_dataset=eval_dataset,
    embed_model=embed_model,
    threshold=0.80,
    k=5,
)

Overall MRR@5:     0.4286
Overall Recall@5:  0.4286

### Per-question analysis

In [34]:
per_q_df = pd.DataFrame(results["per_question"])
per_q_df.head()

,question,contexts,document,retrieved_chunks,gt_chunks,relevance_list,reciprocal_rank,recall,num_relevant
0,What is the order model number for the M12 cable?,[### 17-pin M12 Cable with Fast Ethernet Inter...,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,[| 8-pin terminal |\n\n17-pin M12 Ca...,[### 17-pin M12 Cable with Fast Ethernet Inter...,"[1, 0, 0, 0, 0]",1.0,1.0,1
1,What are the dimensions of the M12-mount housi...,[Fig. 1-1: $46 \times 57.6 \times 25$ mm Mecha...,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,[# 1 Mechanical Dimensions\n\nThe dimensions i...,[Fig. 1-1: $46 \times 57.6 \times 25$ mm Mecha...,"[1, 0, 0, 0, 0]",1.0,1.0,1
2,What are all the pins on the 17-pin connector ...,[| Purple White | 3 | - | - ...,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,[| Do not use it for wiring |\n| Purple | 13 ...,[| Purple White | 3 | - | - ...,"[0, 0, 0, 0, 0]",0.0,0.0,0
3,What communication protocols does the SM2 seri...,"[* Support Serial, TCP, UDP, FTP, Modbus and o...",User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,[Equipment shown in Fig. 1-2\n\nDouble-click t...,"[* Support Serial, TCP, UDP, FTP, Modbus and o...","[0, 0, 0, 0, 0]",0.0,0.0,0
4,List all the LED indicators and what each colo...,[| PWR Indicator | It is a power indicator. Th...,User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN,[# Status LED Description\n\n| Status LED |...,[| PWR Indicator | It is a power indicator. Th...,"[1, 0, 0, 0, 0]",1.0,1.0,1

### Failure cases

In [35]:
# Questions where nothing was retrieved correctly
failures = per_q_df[per_q_df["recall"] == 0.0]
print(f"\n{len(failures)} complete misses:\n")
for _, row in failures.iterrows():
    print(f"  [{row['document']}] {row['question']}")

# Questions where the first relevant chunk wasn't ranked #1
poor_mrr = per_q_df[(per_q_df["recall"] == 1.0) & (per_q_df["reciprocal_rank"] < 1.0)]
print(f"\n{len(poor_mrr)} retrieved but ranked poorly:\n")
for _, row in poor_mrr.iterrows():
    print(f"  RR={row['reciprocal_rank']:.2f} | {row['question']}")
    print(f"  Relevance list: {row['relevance_list']}")

4 complete misses:

  [User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN] What are all the pins on the 17-pin connector that should NOT be used for wiring?
  [User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN] What communication protocols does the SM2 series support?
  [User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN] Is the SM2 SE camera compatible with GigE Vision or GenICam standards?
  [User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN] Can the IO box V1.0 upgrade non-isolated IO to opto-isolated IO?

0 retrieved but ranked poorly:

In [37]:
def inspect_question(per_q_df, index):
    row = per_q_df.iloc[index]
    print(f"Question:     {row['question']}")
    print(f"Contexts: {row['contexts']}")
    print(f"RR: {row['reciprocal_rank']:.2f}  |  Recall: {row['recall']}")
    print(f"\nGT Chunks ({len(row['gt_chunks'])}):")
    for i, c in enumerate(row['gt_chunks']):
        print(f"  [{i}] {c[:200]}...")
    print(f"\nRetrieved Chunks (relevance: {row['relevance_list']}):")
    for i, (chunk, rel) in enumerate(zip(row['retrieved_chunks'], row['relevance_list'])):
        tag = "✓" if rel else "✗"
        print(f"  {tag} [{i}] {chunk[:200]}...")

inspect_question(per_q_df, 0)

Question:     What is the order model number for the M12 cable?
Contexts: ['### 17-pin M12 Cable with Fast Ethernet Interface\n\nOrder Model: VT-M1217P2RJ45-3M(SM2)\n\n']
RR: 1.00  |  Recall: 1.0

GT Chunks (1):
  [0] ### 17-pin M12 Cable with Fast Ethernet Interface

Order Model: VT-M1217P2RJ45-3M(SM2)

...

Retrieved Chunks (relevance: [1, 0, 0, 0, 0]):
  ✓ [0] | 8-pin terminal           |

17-pin M12 Cable with Fast Ethernet Interface 169.254.58.

Order Model: VT-M1217P2RJ45-3M(SM2)

Subnet Mask: 255.255.255.0

Default Gateway: 169.254.58.254

＊ The network...
  ✗ [1] I/O and serial ports

| Pin | Signal    | Signal Source | Designation                                                                    | Cable                    |
| --- | --------- | ------------- ...
  ✗ [2] | Do not use it for wiring |
| Green  | 4   | RS-232 TX | -             | RS-232 serial port output                                                      | DB9 female serial port   |
| Green  | 5   | R...
  ✗ [3] | Do not use it for wiring |
| Purple | 13  | -         | -             | -                                                                              | Do not use it for wiring |
| Yellow | 14  | M...
  ✗ [4] Equipment shown in Fig. 1-2

Double-click the SM-Datum shortcut on the desktop to open up the client software.

| Color  | Pin | Signal    | Signal Source | Designation                                ...

### Per-Document Analysis

In [44]:
doc_summary = per_q_df.groupby("document").agg(
    num_questions=("question", "count"),
    MRR=("reciprocal_rank", "mean"),
    Recall=("recall", "mean"),
).round(4)
print(doc_summary)

                                           num_questions     MRR  Recall
document
User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN              7  0.4286  0.4286

## Evaluate Generation

In [ ]:
judge_prompt = PromptTemplate(
    """You are evaluating an answer.

Question: {question}
Ground Truth: {ground_truth}
Answer: {answer}

Is the answer acceptable? Respond with ONLY 'yes' or 'no'.
"""
)

async def evaluate_with_llm(query_engine, eval_dataset, llm):
    scores = []

    for sample in eval_dataset:
        response = await query_engine.aquery(sample["question"])
        answer = str(response)

        judge_input = judge_prompt.format(
            question=sample["question"],
            ground_truth=sample["ground_truth"],
            answer=answer
        )

        judgment = await llm.acomplete(judge_input)
        is_correct = "yes" in judgment.text.lower()

        scores.append(is_correct)

    accuracy = sum(scores) / len(scores)
    print(f"LLM Judged Accuracy: {accuracy:.2f}")

await evaluate_with_llm(query_engine, eval_dataset, llm)

Retrieval Hit Rate: 1.00
INFO:google_genai.models:AFC is enabled with max remote calls: 10.
** Messages: **
system: You are an expert Q&A system that is trusted around the world.
Always answer the query using the provided context information, and not prior knowledge.
Some rules to follow:
1. Never directly reference the given context in your answer.
2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines.
user: Context information is below.
---------------------
file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 6

|
| Gray  | 6   | DI\_0     | It can be configured as input or output, and is input by default. |
| Black | 7   | GND       | DC Power Supply Negative                                          |
| Red   | 8   | POWER\_IN | DC Power Supply Positive                                          |

You cannot use DB9 female serial port and VCC to power the device at the same time. Otherwise, damaging to power supply may occur.

The I/O definitions in this manual apply only to ContrasTech standard cables for Smart cameras. Connect according to the I/O types and pinout. Using cables with different color codes from other manufacturers may cause incorrect connections and damage the camera. Always use ContrasTech standard cables.

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 5

I/O and serial ports

| Pin | Signal    | Signal Source | Designation                                                                    | Cable                    |
| --- | --------- | ------------- | ------------------------------------------------------------------------------ | ------------------------ |
| 1   | POWER\_IN | -             | Direct current power supply positive                                           | 8-pin terminal           |
| 2   | OUT\_COM  | -             | Output signal ground                                                           | 8-pin terminal           |
| 3   | -         | -             | -                                                                              | Do not use it for wiring |
| 4   | RS-232 TX | -             | RS-232 serial port output                                                      | DB9 female serial port   |
| 5   | RS-232 RX | -             | RS-232 serial port input                                                       | DB9 female serial port   |
| 6   | MDI0+     | -             | Fast Ethernet signal MDI0+                                                     | RJ45 Ethernet connector  |
| 7   | MDI1-     | -             | Fast Ethernet signal MDI1-                                                     | RJ45 Ethernet connector  |
| 8   | GPIO2     | Line 2+       | Non-isolated input                                                             | 8-pin terminal           |
| 9   | IN\_COM   | -             | Input signal ground                                                            | 8-pin terminal           |
| 10  | GPIO3     | Line 3+       | Non-isolated output                                                            | 8-pin terminal           |
| 11  | GND       | -             | Direct current power supply negative                                           | 8-pin terminal           |
| 12  | -         | -             | -                                                                              | Do not use it for wiring |
| 13  | -         | -             | -                                                                              | Do not use it for wiring |
| 14  | MDI0-     | -             | Fast Ethernet signal MDI0-                                                     | RJ45 Ethernet connector  |
| 15  | MDI1+     | -             | Fast Ethernet signal MDI1+                                                     | RJ45 Ethernet connector  |
| 16  | GPIO0     | Line 0+       | Bi-directional non-isolated I/O, and it is the trigger by default.

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 6

| 8-pin terminal           |

17-pin M12 Cable with Fast Ethernet Interface 169.254.58.

Order Model: VT-M1217P2RJ45-3M(SM2)

Subnet Mask: 255.255.255.0

Default Gateway: 169.254.58.254

＊ The network transmission part of the 17-pin cable corresponding to 6th, 7th, 14th, and 15th pins has been made into an RJ45 interface, and there is no need to wire it yourself.

＊ The DB9 serial port connector corresponds to 4th and 5th pins of the device’s 17-pin interface. You cannot use the 12V power plug open line and DB9 female serial port connector at the same time. Otherwise, damaging to power supply may occur.

＊ The 8-pin connector corresponds to other pins of the device’s 17-pin interface. You can wire according to the actual demands.

＊ The open line corresponds to 3rd, 12th, and 13th pins of the device’s 17-pin interface.

i The open lines of the supplied 17-pin cable cannot be wired with the Fig.1-1 device.

The camera password will be restored to Abc1234. We highly recommend you change the password after login.

| Color | Pin | Signal    | Description                                                       |
| ----- | --- | --------- | ----------------------------------------------------------------- |
| Brown | 1   | DO\_5     | -                                                                 |
| Blue  | 2   | DO\_4     | -                                                                 |
| Brown | 3   | DO\_3     | Non-isolated Output                                               |
| Blue  | 4   | DI\_2     | Non-isolated Input                                                |
| White | 5   | DI\_1     | It can be configured as input or output, and is input by default. |
| Gray  | 6   | DI\_0     | It can be configured as input or output, and is input by default.

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 6

| Do not use it for wiring |
| Green  | 4   | RS-232 TX | -             | RS-232 serial port output                                                      | DB9 female serial port   |
| Green  | 5   | RS-232 RX | -             | RS-232 serial port input                                                       | DB9 female serial port   |
| Yellow | 6   | MDI0+     | -             | Fast Ethernet signal MDI0+                                                     | RJ45 Ethernet connector  |
| Orange | 7   | MDI1-     | -             | Fast Ethernet signal MDI1-                                                     | RJ45 Ethernet connector  |
| Blue   | 8   | GPIO2     | Line 2+       | Non-isolated Input

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 6

| Do not use it for wiring |
| Purple | 13  | -         | -             | -                                                                              | Do not use it for wiring |
| Yellow | 14  | MDI0-     | -             | Fast Ethernet signal MDI0-                                                     | RJ45 Ethernet connector  |
| Orange | 15  | MDI1+     | -             | Fast Ethernet signal MDI1+                                                     | RJ45 Ethernet connector  |
| Gray   | 16  | GPIO0     | Line 0+       | Bi-directional non-isolated I/O, and it is the trigger by default.             | 8-pin terminal           |
| White  | 17  | GPIO1     | Line 1+       | Bi-directional non-isolated I/O, and it is used to switch projects by default. | 8-pin terminal           |

17-pin M12 Cable with Fast Ethernet Interface 169.254.58.
---------------------
Given the context information and not prior knowledge, answer the query.
Query: Can I use the 12V power plug open line and DB9 female serial port connector at the same time.?
Answer:
**************************************************
** Response: **
assistant: No, you cannot use the 12V power plug open line and the DB9 female serial port connector simultaneously. Doing so may result in damage to the power supply.
**************************************************


INFO:google_genai.models:AFC is enabled with max remote calls: 10.
** Prompt: **
You are evaluating an answer.

Question: Can I use the 12V power plug open line and DB9 female serial port connector at the same time.?
Ground Truth: No
Answer: No, you cannot use the 12V power plug open line and the DB9 female serial port connector simultaneously. Doing so may result in damage to the power supply.

Is the answer acceptable? Respond with ONLY 'yes' or 'no'.

**************************************************
** Completion: **
yes
**************************************************


INFO:google_genai.models:AFC is enabled with max remote calls: 10.
** Messages: **
system: You are an expert Q&A system that is trusted around the world.
Always answer the query using the provided context information, and not prior knowledge.
Some rules to follow:
1. Never directly reference the given context in your answer.
2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines.
user: Context information is below.
---------------------
file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 3

# Status LED Description

| Status LED    | Description                                                                                                                                            |
| ------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------ |
| PWR Indicator | It is a power indicator. The indicator is red during the device’s power-on process. After the device is powered on, the indicator is green.            |
| LNK Indicator | It is a network status indicator. The indicator is flashing green when the network transmission is normal. Otherwise, it is unlit.                     |
| STS Indicator | It is a status indicator. The indicator is green when the device operates normally. When errors occur during the device starts or operates, it is red. |

Contact our technical support to get the resetting file.

Camera Serial No. J94219768

Contact: +86 571 86888309

Email: support@visiondatum.com

Website: www.contrastech.com

Import Resetting File

For Research Use Only ©2024 Hangzhou Contrastech Co., Ltd. All rights reserved. All trademarks are the property of Hangzhou Contrastech Co., Ltd.

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 6

Equipment shown in Fig. 1-2

Double-click the SM-Datum shortcut on the desktop to open up the client software.

| Color  | Pin | Signal    | Signal Source | Designation                                                                    | Cable type               |
| ------ | --- | --------- | ------------- | ------------------------------------------------------------------------------ | ------------------------ |
| Red    | 1   | POWER\_IN | -             | Direct current power supply positive                                           | 8-pin terminal           |
| Brown  | 2   | GND       | Line 0/1/2/3- | Direct current power supply negative                                           | 8-pin terminal           |
| Purple | 3   | -         | -             | -                                                                              | Do not use it for wiring |
| Green  | 4   | RS-232 TX | -             | RS-232 serial port output

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 4

# 1 Mechanical Dimensions

The dimensions is in millimeters：

The cameras are interfaced to an external circuity via 17-pin connectors located on the housing and contain power, I/O, Ethernet, and serial signals. The interface is threaded. Tightening the interface during use can reduce the loosening of the interface caused by on-site vibration. There are three indicators on the side of the device that show the device status. There are M2/M3 screw holes on the side and bottom of the device for fixing the device.

# Camera Housing and Base Mounting Hole Size(mm)：

| 76                                                                    |                                                                                                                           |    |
| --------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------- | -- |
| 46 (不含线揽)                                                             | 25                                                                                                                        | 30 |
| 3Make sure that the device to be connected is available and selected. | You cannot log in if the device is occupied or unreachable. It must be restored to the available state before logging in. |    |
| camera via the Software.                                              |                                                                                                                           |    |
| 注：线缆折弯空间 30 mm                                                        | camera.                                                                                                                   | 13 |
| 12.5                                                                  | 2-M3                                                                                                                      | 3  |
| 15                                                                    | 2-M3                                                                                                                      | 3  |

Fig. 1-1: 46 × 57.6 × 25 mm Mechanical Dimensions (in mm) of the Smart Cameras with M12-Monut housing (The installation uses M3 screws).

| 46 （不含线缆）      |                                   |            |
| -------------- | --------------------------------- | ---------- |
| 25             | TRAS169.254.90.1 - 169.254.90.254 |            |
| 38             | Static IP                         | IP Address |
| 15             | 169.254.58.                       |            |
| Subnet Mask    | 255.255.255.0                     | 8          |
| 6.5            | 2-M2                              | 3          |
| 2-M2           | 3                                 | 15         |
| 169.254.58.254 |                                   |            |

Fig.

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 18

# I/O Electrical Feature

# Output Signal

The device has one output signal (Line 3) and two configurable bi-directional I/Os (Line 0/1) that can be configured to output signal, and their internal circuit is shown below.

# Non-Isolated Output Signal

GPO

The max. output current is 25 mA.

The camera is occupied by another process. Log out the camera from the current process before you can log into the TDF.

# Output Level

| 输出高电平 | High | 90 % |
| ----- | ---- | ---- |
| 输出低电平 | Low  | 10 % |

When the external voltage is 12 VDC and pull-up resistor is 1 KΩ, output electric feature is shown below.

| Parameter Name          | Parameter Symbol | Value                              |
| ----------------------- | ---------------- | ---------------------------------- |
| Output Logic Level Low  | VL               | 500 mV                             |
| Output Logic Level High | VH               | 12 VDC (external pull-up resistor) |
| Output Falling Delay    | TDF              | 330 ns                             |
| Output Rising Delay     | TDR              | 4.4 μs                             |
| Output Falling Time     | TF               | 116 ns                             |
| Output Rising Time      | TR               | 3.8 μs                             |

# Relation between different external voltages and output logic level low

| External Voltage | VL     |
| ---------------- | ------ |
| 3.3 V            | 180 mV |
| 5 V              | 260 mV |
| 12 V             | 500 mV |
| 24 V             | 900 mV |

file_name: User_Manual_SM2_SE_Camera_CT_Ver.2.5.4_EN.pdf
page: 6

| 8-pin terminal           |
| Blue   | 9   | GND       | Line 0/1/2/3- | Direct current power supply negative                                           | 8-pin terminal           |
| Brown  | 10  | GPIO3     | Line 3+       | Non-isolated output                                                            | 8-pin terminal           |
| Black  | 11  | GND       | -             | Direct current power supply negative                                           | 8-pin terminal           |
| Pink   | 12  | -         | -             | -                                                                              | Do not use it for wiring |
| Purple | 13  |
---------------------
Given the context information and not prior knowledge, answer the query.
Query: How many indicators are there on the side of the device that show the device status?
Answer:
**************************************************
** Response: **
assistant: There are three indicators on the side of the device that show its status.
**************************************************


INFO:google_genai.models:AFC is enabled with max remote calls: 10.
** Prompt: **
You are evaluating an answer.

Question: How many indicators are there on the side of the device that show the device status?
Ground Truth: Three
Answer: There are three indicators on the side of the device that show its status.

Is the answer acceptable? Respond with ONLY 'yes' or 'no'.

**************************************************
** Completion: **
yes
**************************************************


LLM Judged Accuracy: 1.00